### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by alexbyrnes** [cobeylab/imprinting#15]
Package name should be shorter. @kgostic says "imprinting."

Output from "available" package for imprinting looks good.

───────────────────────────────────────────────────────────────────────────────────────────────────────────
Name valid: ✔
Available on CRAN: ✔ 
Available on Bioconductor: ✔
Available on GitHub:  ✔

**Comment by kgostic** [comment]
Thanks Alex! If it's not too hard to change the name I think this sounds great.

**Comment by alexbyrnes** [comment]
Fixed with #27
