### ISSUE TITLE
Possible issue with tidyverse versions

### ISSUE THREAD

**Issue by philarevalo** [cobeylab/imprinting#6]
Just tried to run `get_imprinting_probabilities()` locally and got an error for `read_csv` that might be a version issue of some kind?

```
Error in read_csv("../processed-data/Intensitymatser.csv", show_col_types = F) :
  unused argument (show_col_types = F)
```

I'm running R 4.0.3 and here are the versions of the tidyverse packages on my installation:

```
v ggplot2 3.3.2     v purrr   0.3.4
v tibble  3.0.3     v dplyr   1.0.2
v tidyr   1.1.2     v stringr 1.4.0
v readr   1.3.1     v forcats 0.5.0
```

**Comment by philarevalo** [comment]
And here's the actual code I ran:

```
rm(list = ls())
library(tidyverse)
options(dplyr.summarise.inform = FALSE)
source('calculation_funs.R')
source('data_import_funs.R')


## Get probabilities for the United States in a single observation year
get_imprinting_probabilities(observation_years = c(2011),
                             countries = c('United States'))
```

**Comment by kgostic** [comment]
Thanks Phil. I'll talk to Alex about this. I think you're right that it's a version issue. You're using an old version of readr (1.3.1). Alex and I are using v2.1.2. The `show_col_types` option was introduced in v2.1.2 to quiet a warning message.

I think that options are to include an update.packages('readr') line in the code, or to hard code in the column specifications.
